version: "3.9"

networks:
  minha_rede:
    driver: bridge

services:
  postgres:
    image: postgres:alpine
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - minha_rede

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: meu_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    networks:
      - minha_rede

  frontend:
    build: ./frontend
    container_name: meu_frontend
    restart: always
    networks:
      - minha_rede

  backend:
    build: ./backend
    container_name: meu_backend
    restart: always
    networks:
      - minha_rede

  nginx:
    build: ./nginx
    container_name: meu_nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - minha_rede

volumes:
  pgdata:
  pgadmindata:
